name: Create Release PR

on:
  workflow_dispatch:

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Count today's PRs
        id: pr_count
        run: |
          PR_COUNT=$(gh pr list --base main --state open --search "${{ env.date }} - release" --json title --jq 'length')
          echo "count=$((PR_COUNT + 1))" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find last merged PR from qa to main
        id: last_merge
        run: |
          LAST_PR=$(gh pr list --base main --head qa --state merged --limit 1 --json mergedAt --jq '.[0].mergedAt')
          echo "last_merged=${LAST_PR:-1970-01-01T00:00:00Z}" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get merged PRs into qa since last release
        id: merged_prs
        run: |
          PR_LIST=$(gh pr list --base qa --state merged --json number,title,url,mergedAt --jq \
            '[.[] | select(.mergedAt > "${{ env.last_merged }}") | "- [#" + (.number|tostring) + "](" + .url + "): " + .title] | join("\n")')

          if [[ -z "$PR_LIST" ]]; then
            PR_LIST="No PRs merged since last release."
          fi

          # Output the result for later steps
          echo "::set-output name=pr_titles::$(echo "$PR_LIST" | sed 's/"/\\"/g')"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR from qa to main
        run: |
          # Generate the PR body with Markdown formatting
          BODY="### Included PRs:\n\n${{ steps.merged_prs.outputs.pr_titles }}"
          
          # Create the PR with the formatted title and body
          gh pr create --base main --head qa \
            --title "${{ env.date }} - release ${{ env.count }}" \
            --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
