name: Create Release PR

on:
  workflow_dispatch:

jobs:
  create-release-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Count today's PRs
        id: pr_count
        run: |
          PR_COUNT=$(gh pr list --base main --state open --search "${{ env.date }} - release" --json title --jq 'length')
          echo "count=$((PR_COUNT + 1))" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find last merged PR from qa to main
        id: last_merge
        run: |
          LAST_PR=$(gh pr list --base main --head qa --state merged --limit 1 --json mergedAt --jq '.[0].mergedAt')
          echo "last_merged=${LAST_PR:-1970-01-01T00:00:00Z}" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get merged commits from qa since last release
        id: merged_commits
        run: |
          # Get the list of merge commits in `qa` since the last release.
          COMMIT_LIST=$(git log --oneline --merges --since="${{ env.last_merged }}" --grep='Merge pull request' --pretty=format:'- [#%h](https://github.com/${{ github.repository }}/commit/%H): %s' )

          if [[ -z "$COMMIT_LIST" ]]; then
            COMMIT_LIST="No commits merged since last release."
          fi

          # Store the commit list in a temporary file (safe for multi-line output)
          echo "$COMMIT_LIST" > commit_list.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR from qa to main
        run: |
          # Read the commit list from the temporary file
          BODY="### Included PRs:\n\n$(cat commit_list.txt)\n\n"

          # Create the PR with the formatted title and body
          gh pr create --base main --head qa \
            --title "${{ env.date }} - release ${{ env.count }}" \
            --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
